name: Go Microservices CI

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  test-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [service-driver, service-user, service-support, service-paiement, service-admin, service-auth, service-paiement ]
    defaults:
      run:
        working-directory: ${{ matrix.service }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: go test -v